name: Local Config
version: 0.0.1
schema: v1
models:
  - name: GPT OSS 20B
    provider: lmstudio
    model: openai/gpt-oss-20b
    apiBase: http://127.0.0.1:1234/v1 # if running a remote instance of LM Studio
    roles:
      - chat
      - edit
      - apply
      - autocomplete
